name: Update EPG Data

on:
  schedule:
    - cron: '0 */6 * * *'  # Co 6 godzin
  workflow_dispatch:        # Możliwość ręcznego uruchomienia

jobs:
  update-epg:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        pip install requests beautifulsoup4 lxml aiohttp
    
    - name: Fetch EPG and update data
      env:
        TMDB_API_KEY: ${{ secrets.TMDB_API_KEY }}
      run: |
        python scripts/fetch_epg.py
    
    - name: Commit and push if changed
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add data/movies.json
        git diff --quiet && git diff --staged --quiet || (git commit -m "🤖 Auto-update EPG data" && git push)
